
/**
 * Single source of truth for the /learn/* guided tour: routing (App.tsx),
 * the contents sidebar (ContentsRail.tsx), and the guided-audio tour
 * (GuidedTourContext.tsx, NarrationBar.tsx) all read from this list instead
 * of each maintaining their own copy.
 *
 * `audioSrc` files are generated by `npm run generate-audio` (see
 * scripts/generate-audio.mjs) from the matching `content/narration/*.txt`
 * script and are not committed as placeholders — a lesson without a
 * generated file simply has no narration until one is produced.
 */

export interface CurriculumStep {
  id: string;
  path: string;
  label: string;
  title: string;
  step: number;
  audioSrc: string;
}

const BASE_URL = import.meta.env.BASE_URL.replace(/\/$/, '');

export const curriculum: CurriculumStep[] = [
  { id: 'intro', path: '/learn', label: '1 · Intro', title: 'What is an option?', step: 1, audioSrc: `${BASE_URL}/audio/intro.mp3` },
  { id: 'payoff', path: '/learn/payoff', label: '2 · Payoff', title: 'The payoff at expiry', step: 2, audioSrc: `${BASE_URL}/audio/payoff.mp3` },
  { id: 'distribution', path: '/learn/distribution', label: '3 · Distribution', title: 'The risk-neutral world', step: 3, audioSrc: `${BASE_URL}/audio/distribution.mp3` },
  { id: 'price-structure', path: '/learn/price-structure', label: '4 · Price', title: 'Anatomy of the price', step: 4, audioSrc: `${BASE_URL}/audio/price-structure.mp3` },
  { id: 'time-decay', path: '/learn/time-decay', label: '5 · Time decay', title: 'Time decay', step: 5, audioSrc: `${BASE_URL}/audio/time-decay.mp3` },
  { id: 'greeks', path: '/learn/greeks', label: '6 · Greeks', title: 'The Greeks', step: 6, audioSrc: `${BASE_URL}/audio/greeks.mp3` },
  { id: 'monte-carlo', path: '/learn/monte-carlo', label: '7 · Monte Carlo', title: 'Monte Carlo pricing', step: 7, audioSrc: `${BASE_URL}/audio/monte-carlo.mp3` },
  { id: 'limitations', path: '/learn/limitations', label: '8 · Limitations', title: 'What the model assumes', step: 8, audioSrc: `${BASE_URL}/audio/limitations.mp3` },
];

export const totalSteps = curriculum.length;

export const stepByPath = (path: string): CurriculumStep | undefined =>
  curriculum.find((s) => s.path === path);

export const stepById = (id: string): CurriculumStep | undefined =>
  curriculum.find((s) => s.id === id);
